name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2

    - name: rename worker directory
      working-directory: ../
      run: |

    - name: setup env
      run: |
        echo "name=DATE::$(date +%Y%m%d)" >> $GITHUB_ENV
        echo "name=OCCU_VERSION::$(grep "OCCU_VERSION =" buildroot-external/package/occu/occu.mk | cut -d' ' -f3 | cut -d'-' -f1)" >> $GITHUB_ENV
        echo "name=VERSION::$(grep "OCCU_VERSION =" buildroot-external/package/occu/occu.mk | cut -d' ' -f3 | cut -d'-' -f1).$(date +%Y%m%d)" >> $GITHUB_ENV
        echo "name=GITHUB_SHA7::$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

